#!/usr/bin/env bash

CTR_COL="\e[31m"
USR_COL="\e[34;3m"
RST_COL="\e[0m"
DIR_COL="\e[32;4m"
PMT_COL="\e[7m"
GIT_COL="\e[35;1m"

#outlier...
TIME_COL="\e[3m"

GIT_BRANCH=$(git branch 2> /dev/null | sed -n -e 's/^\* \(.*\)/\1/p')

# compact or naw
case $RESPIO_COMPACT in
	"w")
		ARROW="────────►"
		;;
	"c")
		ARROW="──►"
		;;
	"u")
		ARROW="─►"
		;;
esac

if [[ $RESPIO_SHOW_TIME="yes" ]]; then
	CURRENT_TIME=$(date | sed -r -n "s/.*([0-9][0-9]:[0-9]+:[0-9][0-9]).*/\1/p")
	TOP_PROMPT="[$TIME_COL$CURRENT_TIME$RST_COL]\n╭─($USR_COL$USER@$HOSTNAME$RST_COL)"
else
	TOP_PROMPT="\n╭─($USR_COL$USER@$HOSTNAME$RST_COL)"
fi
if [[ -n $CONTAINER_ID ]]; then
	TOP_PROMPT="$TOP_PROMPT$ARROW{$CTR_COL$CONTAINER_ID$RST_COL}$ARROW[$DIR_COL${PWD/*$HOME/\~}$RST_COL]"
else
	TOP_PROMPT="$TOP_PROMPT$ARROW[$DIR_COL${PWD/*$HOME/\~}$RST_COL]"
fi

if [[ "$GIT_BRANCH" != "" ]]; then 
	TOP_PROMPT="$TOP_PROMPT$ARROW[$GIT_COL$GIT_BRANCH$RST_COL]" 
fi

if [[ -d "/sys/class/power_supply/BAT0" && $RESPIO_SHOW_BAT_CHARGE="yes" ]]; then
	CHARGE_LEVEL=$(cat /sys/class/power_supply/BAT0/capacity)
	MID_PROMPT="┷[$CHARGE_LEVEL%]"
else
	MID_PROMPT="┷"
fi

echo "$TOP_PROMPT\n$MID_PROMPT \$ "
